name 'delivery_build'
maintainer 'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license 'apache2'
description 'Sets up a delivery build node'
version '0.4.27'

depends 'git'
depends 'build-essential'
depends 'chef-sugar'
depends 'delivery-base'
depends 'chef-ingredient', '>= 0.18.0'
