name             'delivery_build'
maintainer       'Chef Software, Inc.'
maintainer_email 'adam@chef.io'
license          'apache2'
description      'Sets up a delivery build node'
long_description 'Sets up a delivery build node'
version          '0.1.5'

depends 'git'
depends 'packagecloud'
